implement charts for SNX Supply and TotalIssuedSynths
Synthetixio/stats pull request #134
Opened 2021-09-04 06:46 UTC by KillerByte

these have been added at the request of the spartan council, specifically for monitoring L2 status

It includes 2 new area charts in the `Synths` section: `SNX Supply` and `Total Issued Synths`. Both of which are able to show Year, Month, and Week.

Also the `Synths` section is enabled for L2, which displays other useful statistics which are mostly ready for display.

Note that the error seen on page load will go away once the global-debt
subgraph for mainnet finishes re-syncing (as there was a change for globl debt recently).

2021-09-04 08:31 UTC, vbstreetz commented
- [ ] Missing i18n entry
<img width="391" alt="Screenshot 2021-09-04 at 11 30 34" src="https://user-images.githubusercontent.com/60554509/132088302-0352f53d-c239-4ac3-adb7-f324d759e59d.png">

2021-09-04 09:45 UTC, vbstreetz commented on translations/en.json
> -	"total-debt": {
revert

2021-09-04 09:46 UTC, vbstreetz requested changes

2021-09-04 09:46 UTC, vbstreetz commented on translations/en.json
> -	"total-debt": {
seems this is still being used

2021-09-09 16:35 UTC, KillerByte commented on translations/en.json
> -	"total-debt": {
fixed https://github.com/Synthetixio/stats/pull/134/commits/d567e313e2bcde2a4c702da7fd1b91f36cca98ef

2021-09-10 10:05 UTC, vbstreetz requested changes

2021-09-10 10:05 UTC, vbstreetz commented on sections/Staking/index.tsx
> +		const value = wei(liquidation.amountLiquidated).toNumber();
should this be divided by 1e18?

2021-09-10 16:53 UTC, vbstreetz approved these changes
Now looking good.

2021-09-10 22:21 UTC, merged